name = "ArsColonies"
author = "TheRealFruitGod"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f58ff0463028deab7bec9172e51284d00cb7874fb5d2fd3827a800c4e7e52268"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
